name: on merging to default branch

on:
   push:
     branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }} 
          ref: develop

      - name: set global attributes
        run: |
          git config --global user.email "bmsteve96@gmail.com"
          git config --global user.name "Benedict Steven"
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }}
      - name: Build
        run: npm install

      - name: get version
        run: |
          PACKAGE_VERSION=$(cat ./package.json | jq '.version' | tr -d '"') 
          echo "::set-output name=PACKAGE_VERSION::$(cat ./package.json | jq '.version' | tr -d '"')"
          echo $PACKAGE_VERSION
        id: version

      - name: Build
        run: npm run build

      - name: test version
        run: echo ${{ steps.version.outputs.PACKAGE_VERSION }}

      - name: bump version actions
        uses: bmsteven/bump-version@1.0.4
        with: 
          GITHUB_TOKEN: ${{secrets.TOKEN}}
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
          APP_NAME: Engineering-blog
          PACKAGE_VERSION: ${{ steps.version.outputs.PACKAGE_VERSION }}

      - name: update develop branch
        run: |
          git add package.json
          git add changelog.md
          git add action
          git commit -m "Skip CI"
          git push