name: on merging to develop

on:
   push:
     branches: 
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: npx yarn

      - uses: ./
        with:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
          DESTINATION_BRANCH: master
          KEYWORD: "publish"
