name: on merging to develop

on:
   push:
     branches: [**]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: npm install

      - uses: ./
        with:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
          DESTINATION_BRANCH: staging
          KEYWORD: "publish"
